# 데이터 구조 접근하기

* 배열을 인자로 처리하는 팬시 검색(Fancy indexing)과 논리 검색(Boolean Indexing)

# 다차원 배열(numpy.array) 팬시 검색과 논리 검색

In [1]:
import numpy as np

## 팬시 검색

### 2차원 배열 만들기

In [2]:
# 3행 3열 배열
a = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9]
             ])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 행을 중심으로 팬시 검색

* 한개의 리스트를 색인 연산의 인자로 전달
* 행을 2차원 배열로 반환

In [5]:
a[0] # 첫 번째 행의 1차원 배열을 조회

array([1, 2, 3])

In [6]:
# 팬시 검색: 리스트를 색인 연산의 인자로 전달, 0행인 2차원 배열을 반환
a[[0]]

array([[1, 2, 3]])

In [7]:
# 0행, 2열의 값
a[0,2]

3

In [8]:
# 팬시 검색: 0행과 2행을 가진 2차원 배열을 반환
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [9]:
# 범위를 벗어나면 오류
try:
    a[[3]]
except Exception as e:
    print(e)

index 3 is out of bounds for axis 0 with size 3


### 행과 열을 조합한 팬시검색

In [10]:
# 0행, 2행 조회
b = a[[0,2]]
b

array([[1, 2, 3],
       [7, 8, 9]])

In [11]:
# 모든행, 0,2열 조회
b[:, [0,2]]

array([[1, 3],
       [7, 9]])

### 두 개의 팬시 검색을 행과 열에 전달

In [12]:
# 두개의 리스트를 사용하면 다차원 배열이 만들어 지지 않는다.
# 순서쌍을 만들어서 해당하는 원소만 팬시 검색으로 처리한다.
# 0행 0열, 2행 2열의 값을 조회
a[[0,2], [0,2]]

array([1, 9])

In [13]:
# 두 개의 행과 두 개의 열을 검색하려면 np.ix_함수를 사용하여야 한다.
# 앞[]의 첫 번째 인수인 0을 뒤의[]에 각각 대입한 list 값 [[0,0], (0,2)]
# 앞[]의 두 번째 인수인 2를 뒤의[]에 각각 대입한 list 값 [(2,0), (2,2)]
a[np.ix_([0,2], [0,2])]

array([[1, 3],
       [7, 9]])

In [14]:
np.ix_([0,2], [0,2])

(array([[0],
        [2]]),
 array([[0, 2]]))

In [15]:
p = np.array([[1, 2, 3],
              [4, 5, 6], 
              [7, 8, 9],
              ['a', 'b', 'c'] 
             ])
p[np.ix_([0,2,3], [1,2])]

array([['2', '3'],
       ['8', '9'],
       ['b', 'c']], dtype='<U11')

In [16]:
np.ix_([0,2,3], [1,2])

(array([[0],
        [2],
        [3]]),
 array([[1, 2]]))

### 팬시 검색은 새로운 배열 사본을 생성하여, 메모리를 공유하지 않는다.

In [17]:
c = a[np.ix_([0,2], [0,2])]

In [18]:
# 메모리 공유하는지 확인
np.may_share_memory(c, a) # 메모리를 공유하지 않는다.

False

## 논리 검색

* 다차원 배열은 비교 연산과 관계 연산을 사용해 검색할 수 있다.

### 논리식 적용

In [19]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 원소별로 비교
a > 5  # 5보다 크면 True

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

### 논리식을 색인 연산에 넣기

In [21]:
# 조건을 만족하는 결과(True)만 조회
a[a>5]

array([6, 7, 8, 9])

### 논리 연산을 묶어서 처리

In [22]:
# 5보다 크고 8보다 작은 값을 True
(a>5) & (a<8)

array([[False, False, False],
       [False, False,  True],
       [ True, False, False]])

In [23]:
# 조건을 만족하는 결과(True)만 조회
a[(a>5) & (a<8)]

array([6, 7])

### 논리 검색은 새로운 배열 사본을 생성하여, 메모리를 공유하지 않는다.

In [24]:
d = a[(a>5) & (a<8)] 

In [25]:
# 메모리 공유하는지 확인
np.may_share_memory(d, a)  # 메모리를 공유하지 않는다.

False

### 검색연산자 내에 관계연산자 사용은 안된다.

In [26]:
try:
    a[(a>5) and (a<8)]
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
