# 판다스의 팬시 검색과 논리 검색

## 팬시 검색

### 다차원 배열로 2차원 배열 만들기

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 10개의 원소를 가진 1차원 배열을 만들어(arrange), 이것을 2차원 배열로 만든다.(reshape)
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 데이터프레임 만들기

In [3]:
df = pd.DataFrame(a, columns=list('abcde')) # 2차원 배열과 columns를 이용해 DataFrame 만들기
df

a  b  c  d  e
0  0  1  2  3  4
1  5  6  7  8  9

### 데이터 프레임 검색

In [4]:
# 열의 레이블로 검색 -> Series로 열을 반환
df['a'] # a열 조회

0    0
1    5
Name: a, dtype: int32

In [5]:
# 팬시 검색으로 하나의 열을 검색 -> DataFrame으로 열을 반환
df[['a']]

a
0  0
1  5

### 여러 열을 검색

In [6]:
df[['a', 'b', 'c']]

a  b  c
0  0  1  2
1  5  6  7

## 논리 검색

* 판다스의 논리 검색은 데이터프레임을 1차원으로 변형한 다음 1차원 논리 조건을 넣어 검색한다.

### 논리식 수행 후 검색

In [7]:
b = a > 5
b

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [8]:
# 판다스의 논리 검색은 각 원소를 조회하지 않는다.
# 판다스의 논리 검색은 행을 기반으로 처리한다. 그래서 True가 들어있는 두 번째행을 4번 출력한다.
df[b]

a  b  c  d  e
1  5  6  7  8  9
1  5  6  7  8  9
1  5  6  7  8  9
1  5  6  7  8  9

In [9]:
# 원하는 원소만 추출하려면 flatten 함수로 다차원 배열을 1차원으로 변형한다.
c = b.flatten() # 다차원 배열을 1차원으로 변환
c

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [10]:
# 판다스의 논리 검색은 데이터프레임을 1차원으로 변형한 다음 1차원 논리 조건을 넣어 검색한다.
df.values.flatten()[c]

array([6, 7, 8, 9])