# 데이터 구조 변경

* 다차원 배열과 데이터프레임으로 만들어진 객체를 하나로 결합하는 방법

## 다차원 배열에 데이터의 행과 열 추가

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.arange(1, 10).reshape(3, 3) # 3행 3열의 2차원 배열
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
b = np.arange(11, 14).reshape(1, 3) # 1행 3열의 2차원 배열
b

array([[11, 12, 13]])

In [4]:
# 수칙축으로 결합할 때는 axis=0(index)
np.append(a, b, axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [5]:
# 수평축으로 결합할 때는 axis=1(columns), b.T는 행과 열을 바꿈(transpose)
np.append(a, b.T, axis=1)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [6]:
b.T

array([[11],
       [12],
       [13]])

## 데이터프레임에 행과 열 추가

In [7]:
df1 = pd.DataFrame([[1, 2], [3, 4]], columns=list('가나'))
df1

가  나
0  1  2
1  3  4

In [8]:
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=list('가나'))
df2

가  나
0  5  6
1  7  8

In [9]:
# 수직축으로 결합(axis=0(index)은 default 값으로 지정하지 않아도 된다.)
# df1.append(df2) # 더이상 사용되지 않음
pd.concat([df1, df2])

가  나
0  1  2
1  3  4
0  5  6
1  7  8

In [10]:
# 수직축으로 결합(행의 레이블을 무시)
# df1.append(df2, ignore_index=True) # 더이상 사용되지 않음
pd.concat([df1, df2], ignore_index=True)

가  나
0  1  2
1  3  4
2  5  6
3  7  8

In [11]:
# 데이터프레임 생성
df3 = pd.DataFrame([[9, 10]], columns=list('가나'))
df3

가   나
0  9  10

In [12]:
# 수직축으로 결합(행의 레이블을 무시)
pd.concat([df1, df3], ignore_index=True)

가   나
0  1   2
1  3   4
2  9  10

In [13]:
# 새로운 열을 가진 데이터프레임 생성
df4 = pd.DataFrame([[11], [12]], columns=list('다'))
df4

다
0  11
1  12

In [14]:
# 수평 결합(axis=1(columns)
pd.concat([df1, df4], axis=1)

가  나   다
0  1  2  11
1  3  4  12