# 수학 함수

# 시그마와 파이 기호

In [1]:
import numpy as np

In [2]:
# 1~10까지 10개의 원소를 가지는 배열 생성
y = np.linspace(1, 10, 10)
y

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## 덧셈

In [3]:
# 다차원 배열의 연산은 벡터화 연산
y + y

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [4]:
# 스페셜 메소드를 이용한 덧셈 연산
y.__add__(y)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [5]:
# 메소드를 이용한 덧셈 연산
np.add(y, y)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## 합

In [6]:
# 합
y.sum()

55.0

In [7]:
# 누적 합산
z = y.cumsum()
z

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

## 곱셈(product)

In [8]:
# 곱셈
y.prod()

3628800.0

In [9]:
# 누적 곱셉
w = y.cumprod()
w

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])