# 축 기준으로 함수 처리

* 다차원 배열과 데이터프레임은 여러 축을 가지고 있어 축에 해당하는 계산을 할 수 있다.

## 다차원 배열의 축에 따른 원소 계산 방식

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 2차원 배열 생성
a = np.arange(1, 11).reshape(2, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
# 배열을 열을 기준으로 합산(axis=0)
np.sum(a, axis=0)

array([ 7,  9, 11, 13, 15])

In [4]:
# 배열을 행을 기준으로 합산(axis=1)
np.sum(a, axis=1)

array([15, 40])

In [5]:
# 열의 최댓값
np.max(a, axis=0)

array([ 6,  7,  8,  9, 10])

In [6]:
# 행의 최댓값
np.max(a, axis=1)

array([ 5, 10])

## 데이터프레임의 레이블에 따른 원소 계산방식

* 행과 열의 레이블이 같은 경우만 계산, 일치하지 않은 경우 NaN 처리

In [7]:
# 3행 3열
df = pd.DataFrame(np.arange(9.).reshape((3,3)),
                  columns=list('bcd'),
                  index=['제주도', '서울시', '경기도'])

In [8]:
df

b    c    d
제주도  0.0  1.0  2.0
서울시  3.0  4.0  5.0
경기도  6.0  7.0  8.0

In [9]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                   columns=list('acd'),
                   index=['충청남도', '서울시', '경기도'])

In [10]:
df1

a    c    d
충청남도  0.0  1.0  2.0
서울시   3.0  4.0  5.0
경기도   6.0  7.0  8.0

In [11]:
# 행과 열이 동일한 레이블이 있는 경우에만 합산
df + df1

a   b     c     d
경기도  NaN NaN  14.0  16.0
서울시  NaN NaN   8.0  10.0
제주도  NaN NaN   NaN   NaN
충청남도 NaN NaN   NaN   NaN

In [12]:
df.add(df1)

a   b     c     d
경기도  NaN NaN  14.0  16.0
서울시  NaN NaN   8.0  10.0
제주도  NaN NaN   NaN   NaN
충청남도 NaN NaN   NaN   NaN

In [13]:
# index 레이블을 기준으로 합산
df.add(df1, axis='index')

a   b     c     d
경기도  NaN NaN  14.0  16.0
서울시  NaN NaN   8.0  10.0
제주도  NaN NaN   NaN   NaN
충청남도 NaN NaN   NaN   NaN

In [14]:
# fill_value=:데이터프레임에 값이 있을 때 없는 레이블의 값을 지정, 레이블이 모두 없는 경우 NaN
df.add(df1, fill_value=0)

a    b     c     d
경기도   6.0  6.0  14.0  16.0
서울시   3.0  3.0   8.0  10.0
제주도   NaN  0.0   1.0   2.0
충청남도  0.0  NaN   1.0   2.0