# 확률의 기초와 원리

# 집합(Set)

* 집합(Set)은 유일한 원소만 가지는 특정 묶음이나 모임이다.

In [1]:
import numpy as np

In [2]:
# 2행 3열의 2차원 배열
a = np.array([[1, 2, 3], [3, 2, 1]])

In [3]:
# 유일한 원소값
np.unique(a)

array([1, 2, 3])

## 원소의 포함관계

In [4]:
# 배열 a에 원소 3이 포함되어 있는지 확인
np.in1d(a, 3)  # 결과는 1차원 배열형태

array([False, False,  True,  True, False, False])

In [5]:
# 포함되어 있는지 확인, 
np.isin(a, 3) # 결과는 a의 차원 형태

array([[False, False,  True],
       [ True, False, False]])

## 차집합(difference)

In [6]:
b = np.array([[1, 2, 7], [4, 5, 6]])

In [7]:
# 다차원 배열의 형상 비교
a.shape == b.shape

True

In [8]:
# 차집합(a-b)
np.setdiff1d(a, b) # 결과는 1차원 배열형태

array([3])

## 교집합(intersect)

In [9]:
# a, b 공통 원소
np.intersect1d(a, b)

array([1, 2])

## 합집합(union)

In [10]:
# a, b 배열 모든 원소
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6, 7])

## 대칭차집합(symmetric difference)

* 대칭차집합 = 합집합 - 교집합

In [11]:
np.setxor1d(a, b)

array([3, 4, 5, 6, 7])